# This file was generated by GoReleaser. DO NOT EDIT.
cask "agents" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "836cd8dd86c3d07347b0995521bea21b74924bc4fe7bd88651551269798d8280"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c701634938b6e27b5806159a2a3c74d612dcaa62b4a46e35d007e599ede5cd69"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b7cbc610fed786ad818626eee5ab381d38d68831d0868dae93a93de117730824"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "315181d1b7304f1478f8c9adb9d275b8f4c59bf2a06239a93e5ed89a1ca75192"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agents"
  desc "Orchestrate parallel AI coding agents in git worktrees and tmux windows"
  homepage "https://github.com/joaovictor3g/agents"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agents"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agents"]
    end
  end

  # No zap stanza required

end
