# This file was generated by GoReleaser. DO NOT EDIT.
cask "agents" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "71263f81580fc413c256bc3ef42a96cad8892ecd7f7be84cdf951fd2a7816976"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b58b3334bd0ac34a3ef2a74e8d560c0d77a22bc963d2ee4cc95629b7c62552d0"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b27ce9322225a9f71f900bccdd2fe6a0029a28c110567099e15bba70809b4c7"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a12287ef10438895c26587fce2c0a6529a0b258a7c65d6f65a7bf521a2927c66"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agents"
  desc "Orchestrate parallel AI coding agents in git worktrees and tmux windows"
  homepage "https://github.com/joaovictor3g/agents"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agents"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agents"]
    end
  end

  # No zap stanza required

end
