# This file was generated by GoReleaser. DO NOT EDIT.
cask "agents" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "fb0eeca929efbc8622d24a6e969e7cddaa011232c92763241e2dac1a1fce56bd"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "885b8eae8e3e298c96c5caffb9286c30edd8a3e34da6ff00ce5b798c4e7920ba"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "88c569124584e78102e1330a5cf794b3f37948c0481532a7370c50b128733865"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c9eb4944c3b453faa5cd045266c482f449eca9ab22009fef3221a33bcb08203"
      url "https://github.com/joaovictor3g/agents/releases/download/v#{version}/agents_#{version}_linux_arm64.tar.gz"
    end
  end

  name "agents"
  desc "Orchestrate parallel AI coding agents in git worktrees and tmux windows"
  homepage "https://github.com/joaovictor3g/agents"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "agents"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/agents"]
    end
  end

  # No zap stanza required

end
